description: |-
  <em><strong>QUADRIGA</strong> + In Kooperation mit <strong>ZEM</strong></em><br><br>
  <strong>Wann:</strong><br> 
  22.01.26 10 Uhr - 23.01.2026 14 Uhr <br><br>
  <strong>Wo:</strong><br> 
  Brandenburgisches Zentrum für Medienwissenschaften (ZeM)<br><br>
  <strong>Adresse:</strong><br>
  Hermann-Elflein-Straße 18, 14467 Potsdam.
  <br><br>
logo: workshop.png
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
