description: |-
  QUADRIGA + In Kooperation mit ZEM
  <strong>Wo:</strong><br> 
  Brandenburgisches Zentrum für Medienwissenschaften (ZeM)<br><br>
  <strong>Adresse:</strong><br>
  fHermann-Elflein-Straße 18, 14467 Potsdam.
logo: workshop.png
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
